all prog:
	cat ../higher.ttl ../characterization.ttl ../manufacturing.ttl  ../modelling.ttl  ../data.ttl ../optimization.ttl  ../twinning.ttl ../battery.ttl  > all_lbco_modules_combined.ttl
	echo
	echo "please now comment out all owl:imports statements, thanks!"
